### ISSUE TITLE
usando el trabajo del compañero Óscar

### ISSUE THREAD

**Issue by mayumy95** [mayumy95/-proyecto_-todo#1]

**Comment by sputnik567** [comment]
tenemos que distribuirnos para saber quien domina algun lenguaje de programacion que no sea html

**Comment by judith-jennifer** [comment]
tenemos  para empezar o mejorar hasta el jueves o para cuando compañeros.

**Comment by mayumy95** [comment]
hasta  el jueves chicos

**Comment by sputnik567** [comment]
se supone que tenemos que subir los commit no se olviden compañeras ya el proyecto esta dense un tiempo y avancen
